### ISSUE TITLE
Out of Memory error when loading model - Only using 1 GPU

### ISSUE THREAD

**Issue by tamha** [black-forest-labs/flux#10]
Hello,
I'm trying to load models using the streamlit app. I have 4 NVIDIA L4, but it only uses 1 and reaches an out of memory error on flux-schnell. Is there a way to make it load on several GPUs ?
Error :
OutOfMemoryError: CUDA out of memory. Tried to allocate 126.00 MiB. GPU 0 has a total capacity of 21.95 GiB of which 54.12 MiB is free. Process 31512 has 0 bytes memory in use. Of the allocated memory 21.70 GiB is allocated by PyTorch, and 13.95 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by bayley** [comment]
Are you loading in `bfloat16`? The model should fit in 24GB.

**Comment by tamha** [comment]
I'm using the default install mentionned in readme. It works with ComfyUI, closing this issue.

**Comment by HuronExplodium** [comment]
This was resolved by switching from the reference code in the repo to comfyui ?  

Curious because I get the exact same error on a 24gb card trying to run demo_gr.py with default everything, nothing else in ram, have 2x24gb cards.

I am rather interested in getting the reference code demo to run.

**Comment by HuronExplodium** [comment]
Turns out what was missing was --ofload which says it offloads the model when idle but seems to also be necessary to boot the demo
